### ISSUE TITLE
Manual input path for accessible use 

### ISSUE THREAD

**Issue by gwiedeman** [UAlbanyArchives/mailbagit#85]
## The problem the component solves

Mailbag is primarily a command line tool, yet many users are unfamiliar or uncomfortable using the typical command line interface. Gooey enables us to build a basic GUI, but this has substantial accessibility problems. Thus we will add another input path, that uses `input()` along with good user guidance to walk thorough all the options for creating a mailbag. The idea is that a user can even double click a `mailbagit.py` file and run through the options without being comfortable on the command line.

Off the top of my head I'm thinking:
* input (validate
* directory or file (validate that it exists and is the expected format)
* mailbag name
* derivatives (validate that these are possible)
* checksum algorithms
* any metadata?
    * field name (option to end adding metadata) 
    * metadata (option to end adding metadata) 
    * repeat

## Relevant part of mailbag spec?

n/a

## Type of component

- [ ] Core
- [ ] Input
- [ ] Attachments
- [ ] Derivatives conversion
- [ ] Reporting/Exporting
- [x] GUI
- [ ] Distribution

## Expected contribution

- [x] Pull Request
- [ ] Comment with proposed solution

## Major challenges or things to keep in mind

This should include the core mailbagit features, but not everything, since asking each option manually will take forever to run and add substantial usability problems. So I think we're looking to strike a balance where we include the minimal options that are commonly used.

Another issue is validation, as it would be a pain to run though all the input questions and then have  it fail with invalid input and have to start the process all over again. So, we'll need to validate input after each `input()` and give users a change to fix issues before continuing.

**Comment by pobocks** [comment]
I think this might be better off re-thought - if we want to do this, rather than another path, I think the thing to do would be to change the required args from required to "prompts if not provided" and maintain a single input path?

It's also worth asking if this actually serves intended purpose - is there a meaningful increase in real usability here?  I think the line of irreducible complexity of bagging operations is higher than the line for "can provide an argument to a command-line program" but I'm not the target audience. 

In any event, I think this'd need to be prioritized after MVP and probably lower than fixing the GUI accessibility issues?
